logo:
  medium: NAV_logo_digital_White.svg

meta:
  name:
    full: Arbeids- og velferdsetaten
    short: Nav
  link:
    home: https://www.nav.no
    github: https://github.com/navikt
  description: |
    Navs samfunnsoppdrag er å bidra til sosial og økonomisk tryggleik og fremme
    overgang til arbeid og aktivitet. Målet er å skape eit inkluderande samfunn,
    eit inkluderande arbeidsliv og ein velfungerande arbeidsmarknad.
  founded: 2006

typography:
  fonts:
    - family: Source Sans 3
      source: google
      weight: [400, 800]
      style: normal
  monospace-block:
    background-color:
      light: neutral-200
      dark: neutral-dark-200

color:
  palette:
    neutral-dark-200: "#1c232f"
    neutral-dark-600: "#777f8d"
    neutral-dark-700: "#8a92a0"
    neutral-dark-800: "#949ba8"
    accent-dark-600: "#4580ca"
    accent-dark-700: "#5f94d8"
    accent-dark-800: "#6d9ddd"
    success-dark-600: "#378f53"
    success-dark-700: "#4ca265"
    success-dark-800: "#5eab72"
    warning-dark-600: "#c56333"
    warning-dark-700: "#de753c"
    warning-dark-800: "#e78040"
    danger-dark-600: "#de4a50"
    danger-dark-700: "#eb6772"
    danger-dark-800: "#ee7685"
    info-dark-600: "#5b839c"
    info-dark-700: "#7396ab"
    info-dark-800: "#7f9fb3"
    brand-magenta-dark-600: "#b16887"
    brand-magenta-dark-700: "#be7f99"
    brand-magenta-dark-800: "#c58aa2"
    brand-beige-dark-600: "#ab705b"
    brand-beige-dark-700: "#c0836e"
    brand-beige-dark-800: "#c78e79"
    brand-blue-dark-600: "#5b839c"
    brand-blue-dark-700: "#7396ab"
    brand-blue-dark-800: "#7f9fb3"
    meta-purple-dark-600: "#936aca"
    meta-purple-dark-700: "#a581d6"
    meta-purple-dark-800: "#ae8cdb"
    meta-lime-dark-600: "#7c8500"
    meta-lime-dark-700: "#8f9800"
    meta-lime-dark-800: "#99a200"

    neutral-200: "#ecedef"
    neutral-600: "#6f7785"
    neutral-700: "#5d6573"
    neutral-800: "#555d6a"
    accent-600: "#2176D4"
    accent-700: "#0063c1"
    accent-800: "#005bb6"
    success-600: "#00893c"
    success-700: "#007629"
    success-800: "#006c1f"
    warning-600: "#ca5000"
    warning-700: "#ac4400"
    warning-800: "#a03e00"
    danger-600: "#e22948"
    danger-700: "#cb0035"
    danger-800: "#bc002a"
    info-600: "#457c9d"
    info-700: "#246b91"
    info-800: "#156389"
    brand-magenta-600: "#b65681"
    brand-magenta-700: "#a93d70"
    brand-magenta-800: "#a33069"
    brand-beige-600: "#ad634a"
    brand-beige-700: "#915541"
    brand-beige-800: "#874e3b"
    brand-blue-600: "#457c9d"
    brand-blue-700: "#246b91"
    brand-blue-800: "#156389"
    meta-purple-600: "#905bd3"
    meta-purple-700: "#7c4abf"
    meta-purple-800: "#7342b6"
    meta-lime-600: "#757c00"
    meta-lime-700: "#646900"
    meta-lime-800: "#5c6100"

  foreground:
    light: "#202733"
    dark: "#dfe1e5"
  background:
    light: "#ffffff"
    dark: "#0e151f"
  primary:
    light: brand-magenta-600
    dark: accent-dark-600
  secondary:
    light: brand-blue-600
    dark: brand-blue-dark-600
  tertiary:
    light: brand-beige-600
    dark: brand-beige-dark-600
  success:
    light: success-600
    dark: success-dark-600
  info:
    light: info-600
    dark: info-dark-600
  warning:
    light: warning-600
    dark: warning-dark-600
  danger:
    light: danger-600
    dark: danger-dark-600
  light:
    light: "#ffffff"
    dark: "#000000"
  dark:
    light: "#49515e"
    dark: "#a5acb6"
  link:
    light: brand-magenta-600
    dark: brand-magenta-dark-800
